trigger:
  - master

pr:
  branches:
    include:
      - '*'

jobs:
  - job: 'Test'

    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        py27:
          python.version: '2.7'
          tox.env: py27
        py35:
          python.version: '3.5'
          tox.env: py35
        py36:
          python.version: '3.6'
          tox.env: py36
        py37:
          python.version: '3.7'
          tox.env: py37
        flake8:
          python.version: '3.6'
          tox.env: flake8
        dist:
          python.version: '3.6'
          tox.env: dist
        docs:
          python.version: '3.6'
          tox.env: docs
        manifest:
          python.version: '3.6'
          tox.env: manifest

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version) for tests'
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: pip install -U pip
      displayName: 'Upgrade pip'

    - script: pip install tox
      displayName: 'Install tox'

    - script: tox -e $(tox.env)
      displayName: 'Run tox -e $(tox.env)'
